[build]
  publish = "."
  command = "echo 'Build completed - using crypto-analyzer.html'"

[[redirects]]
  from = "/"
  to = "/crypto-analyzer.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/crypto-analyzer.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
