[build]
  publish = "."
  command = "echo 'Build completed - Real-time crypto analysis ready'"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/crypto-analyzer.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/crypto-analyzer.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios"]
