[project]
name = "crypto-rocket"
version = "1.0.0"
description = "CryptoRocket - Análise de criptomoedas com indicadores básicos"
requires-python = ">=3.11"
dependencies = [
    "pycoingecko>=3.2.0",
    "requests>=2.32.4",
]
